language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install . coverage"
# command to run tests
script:
  - tests/run_tests.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
