language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install . coverage"
# command to run tests
script:
  - tests/run_tests.sh
notifications:
  irc:
    channels:
    - "chat.freenode.net#robotpy"
    use_notice: true
    skip_join: true
    on_success: change
